### PR TITLE
Introduce trust-free asset swap extension to Payment Request

### PR DESCRIPTION
**Pull request by oleganza**
This extension allows atomic swap of the assets, or btc->assets, or assets->btc, or an arbitrary mix of both.

### CODE REVIEW

**Comment by devongundry** [comment]
@Flavien i think this one is looking great. give it a read and when you think it's good to go, I'd love to be the one to merge this one in if you don't mind. get my feet wet :)

**Comment by Flavien** [comment]
This is minor: in a few places, instead of `client is able to determine`, I think it should read `the client is able to determine` (same with `merchant` vs `the merchant`).

Also, following [these guidelines](http://chris.beams.io/posts/git-commit/#seven-rules) for great git commit messages:

- @devongundry: Can you capitalize the commit message: `Remove gender-specific pronoun`
- @oleganza: Can you remove the unnecessary period (lol!): `Remove unnecessary period`

Otherwise, it looks good to me. Once these are fixed, @devongundry you can go ahead and merge.

**Comment by oleganza** [comment]
@Flavien @devongundry I fixed commit messages, ready for merge now.

**Comment by devongundry** [comment]
@Flavien I made some clarifications and additional grammer fixes. Have a look, and if you're good, I'll merge it in!

**Comment by oleganza** [comment]
@devongundry FYI: I force-pushed grammar fix in your commit message ("grammer" -> "grammar") ;-)

**Comment by devongundry** [comment]
@oleganza ha! the pitfalls of having a best friend with the last name of "Grammer".

**Comment by Flavien** [comment]
Everything looks good guys! Feel free to merge.

**Comment by devongundry** [comment]
@Flavien removed the .DS_Store. Tricky little OSX system file

**Comment by Flavien** [comment]
Cool, that all looks good, feel free to merge.

**Comment by devongundry** [comment]
:+1:

**Pull request merged**
